services:
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgis
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  pg_tileserv:
    image: pramsey/pg_tileserv
    hostname: wikimap_pg_tileserv
    environment:
      DATABASE_URL: postgres://postgres:password@postgis:5432/postgis
    ports:
      - "127.0.0.1:7800:7800"
    depends_on:
      postgis:
        condition: service_healthy
    volumes:
      - ./wikimap/pg_tileserv.toml:/config/pg_tileserv.toml:ro
networks:
  default:
    name: wikimaps_network
volumes:
  postgis_data:
